### ISSUE TITLE
Consistent auth failures in testing.

### ISSUE THREAD

**Issue by fullspectrumdev** [stealth/crash#3]
Built as per instructions, but when I get to testing - everything goes horribly wrong. No matter what I try, authentication fails every time. 

Wondering if there is a subtle bug somewhere that I'm missing, or a problem existing between the user and the keyboard? I had this working before, on different systems, in the past. 

I've tried with the following OpenSSL's and the issue is consistent:

OpenSSL 1.1.1n
OpenSSL 1.1.1t
OpenSSL 3.0.2

```
$ ./crashc -K ./HK_127.0.0.1 -H 127.0.0.1 -l user -i authkey.priv -v

crypted admin shell (C) 2022 Sebastian Krahmer https://github.com/stealth/crash


crashc: starting crypted administration shell
crashc: connecting to 127.0.0.1:2222 ...

Enter PEM pass phrase:
crashc: Major/Minor versions match (3/2)
crashc: Cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
crashc:{
-----BEGIN PUBLIC KEY-----
SNIPPED 
-----END PUBLIC KEY-----
crashc:}
crashc: closing connection.
crashc: No input received. Error. Auth failure?

$ ./crashc -v -K none -i authkey.priv -H 127.0.0.1 -p 2222 -l user

crypted admin shell (C) 2022 Sebastian Krahmer https://github.com/stealth/crash


crashc: starting crypted administration shell
crashc: connecting to 127.0.0.1:2222 ...

Enter PEM pass phrase:
crashc: Major/Minor versions match (3/2)
crashc: Cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
crashc: Hostkey checking disabled!
crashc: client_session::authenticate::unable to complete authentication
```

**Comment by fullspectrumdev** [comment]
This one may be PEBCAK: if I pass *full, absolute paths* to server keys and auth pub key on crashd, it works fine. Self-extract mode also works fine, except in cases where https://github.com/stealth/crash/issues/6 raises its head.

**Comment by stealth** [comment]
crashd server expects to either use full path (detected by leading /) if you want a particular filename to hold the pubkey or it will use the argument
to construct a path similar to ssh with `~/.crash/authorized_keys` (where `.crash` is the default subdir or whatever you pass as arg). So in server mode you essentially omit that parameter and put your key to  `~/.crash/authorized_keys`. The passed filename arg for the client is just 1:1 given to `fopen()`, so you can pass absolute or relative pathnames, as long as you pick the right one.

**Comment by stealth** [comment]
closing
